BAExamApp.MVC/Areas/Admin/Controllers/CityController.cs
using AutoMapper;
using BAExamApp.Dtos.Cities;
using BAExamApp.MVC.Areas.Admin.Models.CityVMs;

namespace BAExamApp.MVC.Areas.Admin.Controllers;

public class CityController : AdminBaseController
{

    private readonly ICityService _cityService;
    private readonly IMapper _mapper;
    public CityController(ICityService cityService, IMapper mapper)
    {
        _cityService = cityService;
        _mapper = mapper;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _cityService.GetAllAsync();
        var cityList = _mapper.Map<IEnumerable<AdminCityListVM>>(result.Data.OrderBy(x => x.Name));

        return View(cityList);
    }


    [HttpPost]
    public async Task<IActionResult> Create(AdminCityCreateVM cityCreateVM)
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelState.Values.SelectMany(x => x.Errors);
            string errorMessages = null!;
            foreach (var error in errors)
            {
                errorMessages += " ," + error.ErrorMessage;
            }
            NotifyError(errorMessages);
            return RedirectToAction(nameof(Index));
        }

        var addResult = await _cityService.AddAsync(_mapper.Map<CityCreateDto>(cityCreateVM));
        if (!addResult.IsSuccess)
        {
            NotifyErrorLocalized(addResult.Message);
            return RedirectToAction(nameof(Index));
        }

        NotifySuccessLocalized(addResult.Message);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete([FromQuery(Name = "id")] Guid id)
    {
        var deleteResult = await _cityService.DeleteAsync(id);
        if (!deleteResult.IsSuccess)
        {
            NotifyErrorLocalized(deleteResult.Message);
        }
        else
        {
            NotifySuccessLocalized(deleteResult.Message);
        }

        return Json(deleteResult);
    }

    [HttpPost]
    public async Task<IActionResult> Update(AdminCityUpdateVM model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var cityUpdateDto = _mapper.Map<CityUpdateDto>(model);
        var updateResult = await _cityService.UpdateAsync(cityUpdateDto);
        if (!updateResult.IsSuccess)
        {
            NotifyErrorLocalized(updateResult.Message);
            return View(model);
        }

        NotifySuccessLocalized(updateResult.Message);
        return RedirectToAction(nameof(Index));
    }
}

BAExamApp.MVC/Areas/Admin/Views/City/CreatePartialView.cshtml
@model AdminCityCreateVM

@{
    ViewData["Title"] = ViewLocalizer["Create_New"];
}

<div class="modal fade" id="createCityModal" tabindex="-1" aria-labelledby="CityAdd" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@ViewLocalizer["Create_New"]</h5>
                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="City" asp-action="Create" class="form" id="create-city">
                <div class="modal-body">
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label col-form-label-lg"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" type="text" class="form-control form-control-lg form-control-solid" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-light me-3" asp-controller="City" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button class="btn btn-primary" type="submit">@SharedLocalizer["Save"]</button>
                </div>
            </form>
        </div>
    </div>
</div>

BAExamApp.MVC/Areas/Admin/Views/City/Index.cshtml
@model IEnumerable<AdminCityListVM>
@{
    ViewData["Title"] = "Index";
}
<div class="card card-docs flex-row-fluid mb-2">
    <!--begin::Card Body-->
    <div class="card-body fs-6 py-15 px-10 py-lg-15 px-lg-15 text-gray-700">
        <!--begin::Section-->
        <div class="p-0">
            <!--begin::Heading-->
            <h5 class="anchor fw-bolder mb-5" id="server-side">
                @SharedLocalizer["List", SharedLocalizer["Cities"]]
            </h5>
            <!--end::Heading-->
            <!--begin::CRUD-->
            <div class="py-5">
                <!--begin::Wrapper-->
                <div class="d-flex flex-stack flex-wrap mb-5">
                    <!--begin::Search-->
                    <div class="d-flex align-items-center position-relative my-1 mb-2 mb-md-0">
                        <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                        <span class="svg-icon svg-icon-1 position-absolute ms-6">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
                                <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
                            </svg>
                        </span>
                        <!--end::Svg Icon-->
                        <input type="text" data-kt-docs-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="@SharedLocalizer["Search"]" />
                    </div>
                    <div class="d-flex justify-content-end" data-kt-docs-table-toolbar="base">
                        <!--begin::Add-->
                        <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createCityModal" title="@SharedLocalizer["Create", SharedLocalizer["City"]]">
                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
                            <span class="svg-icon svg-icon-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1" transform="rotate(-90 11.364 20.364)" fill="currentColor" />
                                    <rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="currentColor" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->@SharedLocalizer["Create", SharedLocalizer["City"]]
                        </a>
                        <!--end::Add-->
                    </div>
                </div>
                <!--end::Wrapper-->
                <!--begin::Datatable-->

                <table id="kt_datatable_example_1" class="table table-row-dashed fs-6 gy-5">
                    <thead>
                        <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                            <th class="sorting" tabindex="0" aria-controls="kt_datatable_example_1" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 175.25px;">@SharedLocalizer["City"]</th>
                            <th class="text-end min-w-100px sorting_disabled" rowspan="1" colspan="1" aria-label="Actions" style="width: 108.25px;">@ViewLocalizer["Operations"]</th>
                        </tr>
                    </thead>
                    <tbody class="text-gray-600 fw-bold">
                        @if (Model.Any())
                        {
                            @foreach (var city in Model)
                            {
                                <tr>
                                    <td class="categories text-start">
                                        <a>
                                            <span class="post_category">@city.Name</span>
                                        </a>
                                    </td>
                                    <td class="text-end">
                                        <a href="#" class="btn btn-light btn-active-light-primary btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end" data-kt-menu-flip="top-end" id="optionsDropdown">
                                            @SharedLocalizer["Options"]
                                            <span class="svg-icon fs-5 m-0">
                                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <polygon points="0 0 24 0 24 24 0 24"></polygon>
                                                        <path d="M6.70710678,15.7071068 C6.31658249,16.0976311 5.68341751,16.0976311 5.29289322,15.7071068 C4.90236893,15.3165825 4.90236893,14.6834175 5.29289322,14.2928932 L11.2928932,8.29289322 C11.6714722,7.91431428 12.2810586,7.90106866 12.6757246,8.26284586 L18.6757246,13.7628459 C19.0828436,14.1360383 19.1103465,14.7686056 18.7371541,15.1757246 C18.3639617,15.5828436 17.7313944,15.6103465 17.3242754,15.2371541 L12.0300757,10.3841378 L6.70710678,15.7071068 Z" fill="currentColor" fill-rule="nonzero" transform="translate(12.000003, 11.999999) rotate(-180.000000) translate(-12.000003, -11.999999)"></path>
                                                    </g>
                                                </svg>
                                            </span>
                                        </a>
                                        <!--begin::Menu-->
                                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4" data-kt-menu="true">
                                            <!--begin::Menu item-->
                                            <div class="menu-item px-3">
                                                <a class="menu-link px-3" data-bs-toggle="modal" data-bs-target="#updateCityModal" asp-route-id="@city.Id" data-city-id = "@city.Id" data-city-name = "@city.Name">@SharedLocalizer["Update"] </a>
                                                <a class="menu-link px-3 deleteAction" data-id="@city.Id">@SharedLocalizer["Delete"]</a>
                                            </div>
                                            <!--end::Menu item-->
                                        </div>
                                        <!--end::Menu-->
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td class="categories text-center">
                                    @SharedLocalizer["No_Data"]
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start">
                        <div class="dataTables_length" id="kt_datatable_example_1_length">
                            <label>
                                <select name="kt_datatable_example_1" aria-controls="kt_datatable_example_1" class="form-select form-select-sm form-select-solid">
                                    <option value="20">20</option>
                                    <option value="50">50</option>
                                </select>
                            </label>
                        </div>
                    </div>
                </div>
                <!--end::Datatable-->
            </div>
            <!--end::CRUD-->
        </div>
        <!--end::Section-->
    </div>
    <!--end::Card Body-->
</div>




<partial name="~/Areas/Admin/Views/City/CreatePartialView.cshtml" model="new AdminCityCreateVM()"></partial>
<partial name="~/Areas/Admin/Views/City/Update.cshtml" model="new AdminCityUpdateVM()"></partial>

@section Scripts
    {
    <script src="~/newlayouts/src/js/custom/apps/user-management/users/list/createCity.js"></script>
    <script src="~/newlayouts/src/js/custom/apps/user-management/users/list/updateCity.js"></script>
    <script src="~/lib/limonte-sweetalert2/sweetalert2.all.js"></script>
    <script>
        var localizedTexts = {
            confirmTitle: '@SharedLocalizer["Confirm_Delete_Title"]', // "fullName adlı admini silmek istediğinize emin misiniz?"
            confirmText: '@SharedLocalizer["Confirm_Delete_Text"]', // "Bu işlem geri alınamaz!"
            confirmButtonText: '@SharedLocalizer["Confirm_Button_Text"]', // "Evet, sil!"
            cancelButtonText: '@SharedLocalizer["Cancel_Button_Text"]' // "Hayır, iptal et"
        };
        var localizer = {
            emptyTable: '@SharedLocalizer["Empty_Data"]',
            info: '@SharedLocalizer["Info"]',
            infoEmpty: '@SharedLocalizer["Info_Empty"]',
            infoFiltered: '@SharedLocalizer["Info_Filtered"]',
            zeroRecords: '@SharedLocalizer["Zero_Records"]',
            lengthMenu: '@SharedLocalizer["Length_Menu"]'
        };
        $(document).ready(function () {
            var dt = $("#kt_datatable_example_1").DataTable({
                lengthMenu: [20, 50],
                dom:
                    '<"row"<"col-sm-12"tr>>' +
                    '<"row"<"col-sm-12 col-md-5"i><"col-sm-12 col-md-7"p>>',
                language: {
                    emptyTable: localizer.emptyTable,
                    info: localizer.info,
                    infoEmpty: localizer.infoEmpty,
                    infoFiltered: localizer.infoFiltered,
                    zeroRecords: localizer.zeroRecords,
                    lengthMenu: localizer.lengthMenu
                }
            });
            $('select[name="kt_datatable_example_1"]').change(function () {
                dt.page.len($(this).val()).draw();
            });

            $('input[data-kt-docs-table-filter="search"]').on('keyup', function () {
                dt.search($(this).val()).draw();
            });
            function updatePaginationArrows() {
                $('#kt_datatable_example_1_previous a').html('<i class="fa fa-chevron-left"></i>');
                $('#kt_datatable_example_1_next a').html('<i class="fa fa-chevron-right"></i>');
            }
            updatePaginationArrows();
            dt.on('draw.dt', function () {
                updatePaginationArrows();
            });

        });
        document.addEventListener('DOMContentLoaded', function () {
            // Dropdown menu element
            var optionsDropdown = document.getElementById('optionsDropdown');

            // Toggle dropdown on click
            optionsDropdown.addEventListener('click', function (e) {
                e.preventDefault();
                var optionsMenu = new KTMenu(optionsDropdown);
                optionsMenu.toggle();
            });
        });
        $(".deleteAction").click(function () {
            const id = $(this).attr("data-id");
            Swal.fire({
                title: `${localizedTexts.confirmTitle}`,
                text: localizedTexts.confirmText,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: localizedTexts.confirmButtonText,
                cancelButtonText: localizedTexts.cancelButtonText
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "GET",
                        url: "@Url.Action("Delete")" + "?id=" + id,
                        success: function (result) {
                            if (result.isSuccess) {
                                setTimeout(() => location.href = "@Url.Action("index")", 1000)
                            }
                        }
                    });
                }
            })
        });
    </script>
}

BAExamApp.MVC/Areas/Admin/Views/City/Update.cshtml
@model AdminCityUpdateVM

@{
    ViewData["Title"] = @ViewLocalizer["Update_City"];
}
<div class="modal fade" id="updateCityModal" tabindex="-1" aria-labelledby="updateCityModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form asp-controller="City" asp-action="Update" method="post" id="updateCityForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateCityModalLabel">@SharedLocalizer["City_Update"]</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3 form-floating">
                        <input asp-for="Name" type="text" class="form-control" required>
                        <label asp-for="Name" class="form-label mb-2">@SharedLocalizer["City_Name"]</label>
                    </div>
                    <input asp-for="Id" type="hidden" />
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary align-self-center ms-2" asp-controller="City" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button type="submit" class="btn btn-primary">@SharedLocalizer["Update"]</button>
                </div>
            </form>
        </div>
    </div>
</div>