BAExamApp.MVC/Areas/Admin/Controllers/ExamController.cs
using AutoMapper;
using BAExamApp.Business.Constants;
using BAExamApp.Core.Enums;
using BAExamApp.Core.Utilities.Results.Concrete;
using BAExamApp.Dtos.ExamClassrooms;
using BAExamApp.Dtos.Exams;
using BAExamApp.Dtos.SendMails;
using BAExamApp.Dtos.StudentExams;
using BAExamApp.Dtos.TrainerProducts;
using BAExamApp.Entities.DbSets;
using BAExamApp.Entities.Enums;
using BAExamApp.MVC.Areas.Admin.Models.ClassroomVMs;
using BAExamApp.MVC.Areas.Admin.Models.ExamEvaluatorVMs;
using BAExamApp.MVC.Areas.Admin.Models.ExamVMs;
using BAExamApp.MVC.Areas.Trainer.Models.ExamVMs;
using BAExamApp.MVC.Areas.Trainer.Models.QuestionVMs;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using NuGet.Versioning;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Security.Claims;

namespace BAExamApp.MVC.Areas.Admin.Controllers;

public class ExamController : AdminBaseController
{
    private readonly IExamService _examService;
    private readonly IMapper _mapper;
    private readonly IClassroomProductService _classroomProductService;
    private readonly ITrainerProductService _trainerProductService;
    private readonly IExamEvaluatorService _examEvaluatorService;
    private readonly IStudentService _studentService;
    private readonly IStudentExamService _studentExamService;
    private readonly IStudentQuestionService _studentQuestionService;
    private readonly IHttpContextAccessor _contextAccessor;
    private readonly IClassroomService _classroomService;
    private readonly IExamRuleService _examRuleService;
    private ITrainerService _trainerService;
    private readonly IUserService _userService;
    private readonly ISendMailService _sendMailService;
    private readonly IMemoryCache _memoryCache;
    private readonly IRabbitMQPublishService _rabbitMQPublishService;

    public ExamController(IExamService examService, IMapper mapper, IClassroomProductService classroomProductService, ITrainerProductService trainerProductService, IExamEvaluatorService examEvaluatorService, IStudentService studentService, IStudentExamService studentExamService, IStudentQuestionService studentQuestionService, IHttpContextAccessor contextAccessor, IClassroomService classroomService, IExamRuleService examRuleService, ITrainerService trainerService, IUserService userService, ISendMailService sendMailService, IMemoryCache memoryCache,IRabbitMQPublishService rabbitMQPublishService)
    {
        _examService = examService;
        _mapper = mapper;
        _classroomProductService = classroomProductService;
        _trainerProductService = trainerProductService;
        _examEvaluatorService = examEvaluatorService;
        _studentService = studentService;
        _studentExamService = studentExamService;
        _studentQuestionService = studentQuestionService;
        _contextAccessor = contextAccessor;
        _classroomService = classroomService;
        _examRuleService = examRuleService;
        _trainerService = trainerService;
        _userService = userService;
        _sendMailService = sendMailService;
        _memoryCache = memoryCache;
        _rabbitMQPublishService = rabbitMQPublishService;
    }
    [HttpGet]
    public async Task<IActionResult> Index()
    {

        

        ViewBag.Classrooms = await GetClassrooms();
        ViewBag.ExamRules = await GetExamRules();
        ViewBag.ExamCreationTypes = GetExamCreationTypes();
        ViewBag.ExamTypes = GetExamTypes();

        return View(new List<AdminExamListVM>());
    }

    [HttpGet]
    public async Task<IActionResult> StartExam(Guid id)
    {
        string link = Url.Action("StartExam", "exam", new { Area = "Student" }, Request.Scheme);

        var examResult = await _examService.GetStudentsInfosByExamIdAsync(id, link);
        var examStarted = await _examService.GetByIdAsync(id);
        if (!examResult.IsSuccess)
        {
            NotifyWarningLocalized(examResult.Message);
            return Json(new { success = true, message = Messages.ExamStartedMailError });
        }
        NotifySuccessLocalized(Messages.ExamStartedSuccessfully);
        _memoryCache.Set("examStarted", examStarted.Data.Id, TimeSpan.FromMinutes(10));
        return Json(new { success = true, message = Messages.ExamStartedSuccessfully });
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AdminExamCreateVM examCreateVM)
    {
        if (ModelState.IsValid)
        {
            var uniqueStudentExamIds = new HashSet<Guid>();
            var studentExams = new List<StudentExamCreateDto>();
            var examClassrooms = new List<ExamClassroomsCreateDto>();
            var examCreateDto = _mapper.Map<ExamCreateDto>(examCreateVM);

            if (examCreateVM.forClassroom && examCreateVM.ExamClassroomsIds != null)
            {
                foreach (var classroomId in examCreateVM.ExamClassroomsIds)
                {
                    var students = await _studentService.GetAllByClassroomIdAsync(classroomId);
                    examClassrooms.Add(new() { ClassroomId = classroomId });
                    if (students.Data != null && students.Data.Count > 0)
                    {
                        foreach (var student in students.Data)
                        {
                            var exam = await _studentExamService.GetAllExamsByStudentIdAsync(student.Id);

                            if (uniqueStudentExamIds.Add(student.Id))
                            {
                                studentExams.Add(new() { StudentId = student.Id });
                            }
                        }
                    }
                    else
                        NotifyErrorLocalized(students.Message);
                }
            }
            else
            {
                if (examCreateVM.StudentIds != null && examCreateVM.StudentIds.Count > 0)
                {
                    foreach (var studentId in examCreateVM.StudentIds)
                    {
                        if (uniqueStudentExamIds.Add(studentId))
                        {
                            studentExams.Add(new() { StudentId = studentId });
                        }
                    }
                    examClassrooms = examCreateVM.ExamClassroomsIds.Select(id => new ExamClassroomsCreateDto { ClassroomId = id }).ToList();
                }
                else
                {
                    NotifyErrorLocalized(Messages.NoAvailableStudent);
                    return RedirectToAction(nameof(Index));
                }
            }
            examCreateDto.StudentExams = studentExams;
            examCreateDto.ExamClassroomsIds = examClassrooms;
            var examRule = (await _examRuleService.GetByIdAsync(examCreateVM.ExamRuleId)).Data;
            var questionListResult = await _studentQuestionService.CreateQuestionPoolForExamRuleSubtopicsAsync(examRule.ExamRuleSubtopics);
            var adminId = _contextAccessor?.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var adminEmail = await _userService.GetEmailByUserId(adminId, Roles.Admin);

            List<string> examDetail = new List<string>();

            if (questionListResult.IsSuccess)
            {
                var examResult = await _examService.AddAsync(examCreateDto);

                if (examResult.IsSuccess)
                {
                    var studentQuestionResult = await _studentQuestionService.AddRangeForExamIdAsync(examResult.Data.Id);

                    if (studentQuestionResult.IsSuccess)
                    {
                        var studentExamResult = await _studentExamService.GetAllByExamIdAsync(examResult.Data.Id);

                        string link = Url.Action("StartExam", "exam", new { Area = "Student" }, Request.Scheme);

                        if (studentExamResult.IsSuccess)
                        {
                            foreach (var studentExam in studentExamResult.Data)
                            {
                                var studentResult = await _studentService.GetByIdAsync(studentExam.StudentId);
                                if (studentResult.IsSuccess)
                                {
                                    var email = await _sendMailService.GetStudentEmailById(studentExam.StudentId);

                                    var classRoomResult = await _classroomService.GetAsync(x => examCreateVM.ExamClassroomsIds.Contains(x.Id) && studentExam.ClassroomNames.Contains(x.Name));

                                    examDetail.Add($"{studentExam.ExamName}" + "*?*" + $"{classRoomResult.Data.Name}" + "*?*" + $"{studentExam.ExamDateTime}" + "*?*" + $"{email}" + "*?*" + $"{link}/{studentExam.Id}");
                                }

                            }
                            _rabbitMQPublishService.EnqueueModel(new TrainerNewExamMailDto() { TrainerEmailAdress = adminEmail, StudentContents = examDetail }, RabbitMQQueueNames.EmailToTrainerNewExam);


                        }
                        NotifySuccessLocalized(examResult.Message);
                        return RedirectToAction(nameof(Index));
                    }

                    NotifyErrorLocalized(studentQuestionResult.Message);
                }
                else
                {
                    NotifyErrorLocalized(examResult.Message);
                }
            }
            else
            {
                NotifyErrorLocalized(questionListResult.Message);
            }
        }

        ViewBag.Classrooms = await GetClassrooms();
        ViewBag.ExamRules = await GetExamRules();
        ViewBag.ExamTypes = GetExamTypes();
        ViewBag.ExamCreationTypes = GetExamCreationTypes();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id)
    {
        var exam = await _examService.GetDetailsByIdAsync(id);

BAExamApp.MVC/Areas/Trainer/Views/Exam/Create.cshtml
@model TrainerExamCreateVM

@{
    ViewData["Title"] = @ViewLocalizer["Create_Exam"];
}
<div class="card py-16">
    <!--begin::Card header-->
    <div class="ps-9 pt-6">
        <h1 class="text-dark fw-bolder fs-1">@ViewLocalizer["Create_Exam"]</h1>
    </div>
    <!--end::Card header-->
    <div class="card-body">

        <form asp-action="Create" asp-controller="Exam" asp-area="Trainer" class="form" enctype="multipart/form-data" method="post">
            <div class="row mb-3">
            <div class="col-sm-6 ">
                <div class="fv-row form-floating mb-7">
                        <input asp-for="ExamDateTime" type="datetime" asp-format="{0:dd/MM/yyyy HH:mm}" class="form-control form-control-solid" id="ExamDateTime" />
                    <label asp-for="ExamDateTime">@ViewLocalizer["Exam_Date_and_Time"]</label>
                    <span asp-validation-for="ExamDateTime" class="text-danger"></span>
                </div>
            </div>

            <div class="col-sm-6 ">
                <div class="fv-row form-floating mb-7">
                    <input class="form-control form-control-solid" id="ExamDuration"  asp-for="ExamDuration">
                    <label asp-for="ExamDuration">@ViewLocalizer["Exam_Duration"]</label>
                    <span asp-validation-for="ExamDuration" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="fv-row form-floating mb-7">
                    <input type="number" class="form-control form-control-solid" asp-for="MaxScore">
                        <label asp-for="MaxScore">@SharedLocalizer["Max_Score"]</label>
                    <span asp-validation-for="MaxScore" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6 ">
                <div class="fv-row form-floating mb-7">
                    <input type="number" class="form-control form-control-solid" asp-for="BonusScore">
                        <label asp-for="BonusScore">@SharedLocalizer["Bonus_Score"]</label>
                    <span asp-validation-for="BonusScore" class="text-danger"></span>
                </div>
            </div>
                <div class="col-sm-6 ">
                    <div class="fv-row form-floating mb-7">
                        <select class="form-select form-select-sm form-select-solid" asp-for="ExamType" onchange="onExamTypeChange()">
                        <option value="" disabled selected>@SharedLocalizer["Choose"]</option>
                            @foreach (SelectListItem examType in ViewBag.ExamTypes)
                            {
                            <option value="@examType.Value">@SharedLocalizer[$"{examType.Text}"]</option>
                            }
                        </select>
                        <label class="fw-bold fs-6 mb-2" asp-for="ExamType">@SharedLocalizer["Exam_Type"]</label>
                    <span asp-validation-for="ExamType" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6 ">
                    <div class="fv-row form-floating mb-7">
                        <select class="form-select form-select-sm form-select-solid" asp-for="ExamRuleId">
                        <option value="" disabled selected>@SharedLocalizer["Choose"]</option>
                        </select>
                        <label class="fw-bold fs-6 mb-2" asp-for="ExamRuleId"></label>
                        <span asp-validation-for="ExamRuleId" class="text-danger"> </span>
                    </div>
                </div>
                <div class="col-sm-6 ">
                    <div class="fv-row form-floating mb-7">
                        <select class="form-select form-select-sm form-select-solid" asp-for="ExamCreationType" onchange="onExamTypeChange()">
                            <option value="" disabled selected>@SharedLocalizer["Choose"]</option>
                            @foreach (SelectListItem examCreationTypes in ViewBag.ExamCreationTypes)
                            {
                                <option value="@examCreationTypes.Value">@SharedLocalizer[$"{examCreationTypes.Text}"]</option>
                            }
                        </select>
                        <label class="fw-bold fs-6 mb-2" asp-for="ExamCreationType"></label>
                        <span asp-validation-for="ExamCreationType" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6 ">
                    <div class="fv-row mb-7">
                        <label class="form-check form-switch form-check-custom form-check-solid">
                            <div>
                                <label class="form-check-label fw-bold text-muted" for="ogrenci" id="ogrenciLabel">@ViewLocalizer["Create_Exam_Student"]</label>
                            </div>
                            <div>
                                <input class="form-check-input" asp-for="forClassroom" type="checkbox" id="ogrenci" onchange="onSwitchChange()">
                            </div>
                            <div>
                                <label class="form-check-label fw-bold text-muted" for="sinif" id="sinifLabel">@ViewLocalizer["Create_Exam_Class"]</label>
                            </div>
                        </label>
                    </div>
                </div>
                
                <div class="card" id="studentclassroomcard">
                    <div class="col-sm-6">
                        <div class="fv-row form-floating mb-7">
                            <select asp-for="ExamClassroomsIds" asp-items="@ViewBag.ClassroomList" class="form-select form-select-lg form-select-solid p-3" data-control="select2" data-close-on-select="false" data-allow-clear="false" multiple="multiple" data-search="false">
                            </select>
                            <label class="fw-bold fs-6 mt-n2" asp-for="ExamClassroomsIds">@SharedLocalizer["Exam_Classroom"]</label>
                            <span asp-validation-for="ExamClassroomsIds" class="text-danger"></span>
                        </div>
                    </div>

                    <br />
             <div id="studentArea">
                <div class="col-sm-6">
                    <div class="fv-row form-floating mb-7">
                                <select asp-for="StudentIds" class="form-select form-select-lg form-select-solid p-3" data-control="select2" data-close-on-select="false" data-allow-clear="false" multiple="multiple" data-search="false" id="studentSelect" >
                            </select>
                            <label class="fw-bold fs-6 mb-2" asp-for="StudentIds">Öğrenciler</label>
                            <span asp-validation-for="StudentIds" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="fv-row form-floating mb-7">
                            <textarea class="form-control form-control-solid" asp-for="Description" class="form-control"></textarea>
                            <label class="fw-bold fs-6 " asp-for="Description">Açıklama</label>
                            <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
              </div>
                <div class="form-actions">
                        <a asp-controller="Home" asp-action="Index" class="btn btn-danger" type="reset" data-kt-contacts-type="cancel">@SharedLocalizer["Cancel"]</a>
                        <button type="submit" data-kt-contacts-type="submit" class="btn btn-success">@SharedLocalizer["Save"]</button>
                        
                </div>
            </div>
            </div>
            </form>
    </div>
</div>

@section Scripts{
    <script src="~/newLayouts/dist/assets/plugins/global/plugins.bundle.js"></script>
     <script src="~/js/select2.js"></script>
     <script src="~/lib/trainer/js/createexamforstudent.js"></script>
    <script>
        $("#ExamDateTime").flatpickr({
            enableTime: true, // Saat seçeneğini etkinleştir
            minDate: "today", // Bugünden önceki tarihleri devre dışı bırak
            dateFormat: "d/m/Y H:i", // Düzeltilmiş format
            locale: "tr", // Türkçe dil desteği
            time_24hr: true // 24 saat formatını kullan
        });
    </script>
    <script>
      
        $("#ExamDuration").flatpickr({
            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
            time_24hr: true,
        });
    </script>
    <script>
        $(document).ready(function () {
    var classroomStudents = {};
    var selectedStudents = [];

    $('#ExamClassroomsIds').on('change', function () {
        var selectedClassrooms = $(this).val();

        selectedStudents = $('#studentSelect').val() || [];

        var allStudents = [];
        selectedClassrooms.forEach(function (classroomId) {
            if (classroomStudents[classroomId]) {
                allStudents = allStudents.concat(classroomStudents[classroomId]);
            } else {
                $.ajax({
                    url: '/Trainer/Exam/GetStudentsByClassroom',
                    type: 'GET',
                    data: { classroomId: classroomId },
                    success: function (students) {
                        classroomStudents[classroomId] = students;
                        allStudents = allStudents.concat(students);
                        updateStudentSelect(allStudents);
                    }
                });
            }
        });

        updateStudentSelect(allStudents);
    });

    function updateStudentSelect(students) {
        var studentSelect = $('#studentSelect');
        studentSelect.empty();

        students.forEach(function (student) {
            var isSelected = selectedStudents.indexOf(student.value) > -1;
            var newOption = new Option(student.text, student.value, isSelected, isSelected);
            studentSelect.append(newOption);
        });

        studentSelect.trigger('change');
    }

    var switchElement = $("#ogrenci");
    var studentArea = $("#studentArea");
    var ogrenciLabel = $("#ogrenciLabel");
    var sinifLabel = $("#sinifLabel");

    switchElement.on('change', function () {
        if ($(this).is(':checked')) {
            studentArea.hide();
            sinifLabel.css('font-weight', 'bold');
            ogrenciLabel.css('font-weight', 'normal');
        } else {
            studentArea.show();
            ogrenciLabel.css('font-weight', 'bold');
            sinifLabel.css('font-weight', 'normal');
        }
    });

    if (switchElement.is(':checked')) {
        studentArea.hide();
        sinifLabel.css('font-weight', 'bold');
        ogrenciLabel.css('font-weight', 'normal');
    } else {
        studentArea.show();
        ogrenciLabel.css('font-weight', 'bold');
        sinifLabel.css('font-weight', 'normal');
    }
});
    </script>
}

BAExamApp.MVC/Areas/Trainer/Views/Exam/Update.cshtml
@model TrainerExamUpdateVM

@{
    ViewData["Title"] = @ViewLocalizer["Update_Exam"];
}

<div class="modal fade" id="kt_modal_new_target" tabindex="-1" aria-hidden="true">
    <!--begin::Modal dialog-->
    <div class="modal-dialog modal-dialog-centered mw-1000px">
        <!--begin::Modal content-->
        <div class="modal-content rounded">
            <!--begin::Modal header-->
            <div class="modal-header mb-7">

                <h2 class="fw-bolder">@ViewLocalizer["Update_Exam"]</h2>

                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                    <!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
                    <span class="svg-icon svg-icon-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor" />
                        </svg>
                    </span>
                </div>
            </div>
            <div class="modal-body scroll-y px-10 px-lg-15 pt-0 pb-15">
                <form asp-action="Update" asp-controller="Exam" asp-area="Trainer" id="kt_modal_new_target_form" class="form" enctype="multipart/form-data" method="post">
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="hidden" asp-for="Id" />
                            <input asp-for="Name" type="hidden" class="form-control form-control-solid">
                            <div class="fv-row form-floating mb-7">
                                <input asp-for="ExamDateTime" class="form-control form-control-solid" id="ExamDateTime" asp-format="{0:dd/MM/yyyy HH:mm}">
                                <label asp-for="ExamDateTime">@ViewLocalizer["Exam_Date_and_Time"]</label>
                                <span asp-validation-for="ExamDateTime" class="text-danger"></span>
                            </div>
                            <div class="fv-row form-floating mb-7">
                                <select asp-for="ExamType" asp-items="ViewBag.ExamTypes" class="form-select form-select-sm form-select-solid" id="ExamType">
                                </select>
                                <label class="fw-bold fs-6 mb-2" asp-for="ExamType">@SharedLocalizer["Exam_Type"]</label>
                                <span asp-validation-for="ExamType" class="text-danger"></span>
                            </div>



                            <div class="fv-row form-floating mb-7">
                                <select asp-for="ExamRuleId" asp-items="ViewBag.ExamRuleList" class="form-select form-select-sm form-select-solid" id="ExamRuleId">
                                    <option value="" disabled selected>@SharedLocalizer["Choose"]</option>
                                </select>
                                <label class="fw-bold fs-6 mb-2" asp-for="ExamRuleId"></label>
                                <span asp-validation-for="ExamRuleId" class="text-danger"> </span>
                            </div>



                            <div class="fv-row form-floating mb-7">
                                <select class="form-select form-select-sm form-select-solid" asp-for="ExamCreationType" asp-items="ViewBag.ExamCreationTypes"  id="ExamCreationType">
                                </select>
                                <label class="fw-bold fs-6 mb-2" asp-for="ExamCreationType"></label>
                                <span asp-validation-for="ExamCreationType" class="text-danger"></span>
                            </div>
                            <div class="fv-row form-floating mb-7">
                                <select asp-for="ExamClassroomsIds" asp-items="ViewBag.className" class="form-select form-select-lg form-select-solid p-3" data-control="select2" data-close-on-select="false" data-allow-clear="false" multiple="multiple" data-search="false"  id="ExamClassroomsIds">
                                </select>
                                <label class="fw-bold fs-6 mt-n2" asp-for="ExamClassroomsIds">Exam Classrooms</label>
                                <span asp-validation-for="ExamClassroomsIds" class="text-danger"></span>
                            </div>
                            <div id="studentArea" class="fv-row form-floating mb-7">
                                <select asp-for="StudentIds" class="form-select form-select-lg form-select-solid p-3" data-control="select2" data-close-on-select="false" data-allow-clear="false" multiple="multiple" data-search="false" id="studentSelect">
                                </select>
                                <label class="fw-bold fs-6 mb-2" asp-for="StudentIds">Öğrenciler</label>
                                <span asp-validation-for="StudentIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="fv-row form-floating mb-7">
                                <input asp-for="ExamDuration" class="form-control form-control-solid" id="ExamDuration">
                                <label asp-for="ExamDuration">@ViewLocalizer["Exam_Duration"]</label>
                                <span asp-validation-for="ExamDuration" class="text-danger"></span>
                            </div>
                            <div class="fv-row form-floating mb-7">
                                <input type="number" class="form-control form-control-solid" asp-for="MaxScore" id="MaxScore">
                                <label asp-for="MaxScore">@ViewLocalizer["Max_Score"]</label>
                                <span asp-validation-for="MaxScore" class="text-danger"></span>
                            </div>
                            <div class="fv-row form-floating mb-7">
                                <input type="number" class="form-control form-control-solid" asp-for="BonusScore" id="BonusScore">
                                <label asp-for="BonusScore">@ViewLocalizer["Bonus_Score"]</label>
                                <span asp-validation-for="BonusScore" class="text-danger"></span>
                            </div>

                            <div class="fv-row form-floating mb-7">
                                <textarea class="form-control form-control-solid" asp-for="Description" class="form-control" id="Description"></textarea>
                                <label class="fw-bold fs-6 " asp-for="Description">Açıklama</label>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="fv-row form-floating mb-7">
                                <textarea class="form-control form-control-solid" asp-for="TrainerExplanation" class="form-control"  id="TrainerExplanation"></textarea>
                                <label class="fw-bold fs-6 " asp-for="TrainerExplanation">Güncelleme Açıklaması</label>
                                <span asp-validation-for="TrainerExplanation" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="fv-row mb-7">
                            <label class="form-check form-switch form-check-custom form-check-solid">
                                <div>
                                    <label class="form-check-label fw-bold text-muted" for="ogrenci" id="ogrenciLabel">Öğrenciye Sınav Oluştur</label>
                                </div>
                                <div>
                                    <input class="form-check-input" asp-for="forClassroom" type="checkbox" id="ogrenci" onchange="onSwitchChange()">
                                </div>
                                <div>
                                    <label class="form-check-label fw-bold text-muted" for="sinif" id="sinifLabel">Sınıfa Sınav Oluştur</label>
                                </div>
                            </label>
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="reset" id="kt_modal_new_target_cancel" class="btn btn-light me-3">@SharedLocalizer["Back_List"]</button>
                        <button type="submit" id="kt_modal_new_target_submit" class="btn btn-primary">
                            <span class="indicator-label">@SharedLocalizer["Save"]</span>
                            <span class="indicator-progress">
                                Please wait...
                                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                            </span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/newLayouts/dist/assets/plugins/global/plugins.bundle.js"></script>
    <script src="~/js/select2.js"></script>
    <script src="~/lib/trainer/js/createexamforstudent.js"></script>
}