BAExamApp.MVC/Areas/Admin/Controllers/SubjectController.cs
using AutoMapper;
using BAExamApp.Dtos.Subjects;
using BAExamApp.MVC.Areas.Admin.Models.SubjectVMs;
using BAExamApp.MVC.Extensions;

namespace BAExamApp.MVC.Areas.Admin.Controllers;

public class SubjectController : AdminBaseController
{
    private readonly ISubjectService _subjectService;
    private readonly IMapper _mapper;
    public SubjectController(ISubjectService subjectService, IMapper mapper)
    {
        _subjectService = subjectService;
        _mapper = mapper;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var getSubjectListResult = await _subjectService.GetAllAsync();
        var subjectList = _mapper.Map<List<AdminSubjectListVM>>(getSubjectListResult.Data);
        return View(subjectList);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AdminSubjectCreateVM viewModel)
    {
        if (!ModelState.IsValid)
        {
            var errors = ModelState.Values.SelectMany(x => x.Errors);
            string errorMessages = null!;

            foreach (var error in errors)
            {
                errorMessages += " ," + error.ErrorMessage;
            }

            NotifyError(errorMessages);

            return RedirectToAction(nameof(Index));
        }

        SubjectCreateDto subjectCreateDto = _mapper.Map<SubjectCreateDto>(viewModel);

        subjectCreateDto.Name = StringExtensions.TitleFormat(viewModel.Name);

        var createSubjectResult = await _subjectService.AddAsync(subjectCreateDto);
        if (!createSubjectResult.IsSuccess)
        {
            NotifyErrorLocalized(createSubjectResult.Message);
            return RedirectToAction(nameof(Index));
        }
        NotifySuccessLocalized(createSubjectResult.Message);
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id)
    {
        var subject = await _subjectService.GetDetailsByIdAsync(id);
        if (subject.IsSuccess)
        {
            return View(_mapper.Map<AdminSubjectDetailVM>(subject.Data));
        }
        NotifyErrorLocalized(subject.Message);
        return RedirectToAction(nameof(Index));
    }

    //[HttpGet]
    //public async Task<IActionResult> Update(Guid id)
    //{
    //    var getResult = await _subjectService.GetByIdAsync(id);
    //    if (!getResult.IsSuccess)
    //    {
    //        NotifyErrorLocalized(getResult.Message);
    //        return RedirectToAction(nameof(Index));
    //    }

    //    var updateSubjectResult = _mapper.Map<AdminSubjectUpdateVM>(getResult.Data);

    //    return View(updateSubjectResult);
    //}

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(AdminSubjectUpdateVM viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(nameof(Index));
        }

        var updateSubjectDto = _mapper.Map<SubjectUpdateDto>(viewModel);

        updateSubjectDto.Name = StringExtensions.TitleFormat(viewModel.Name);

        var updateResult = await _subjectService.UpdateAsync(updateSubjectDto);
        if (!updateResult.IsSuccess)
        {
            NotifyErrorLocalized(updateResult.Message);
        }
        else
        {
            NotifySuccessLocalized(updateResult.Message);
        }
        return RedirectToAction(nameof(Index));
    }


    [HttpGet]
    public async Task<IActionResult> Delete(Guid id)
    {
        var subjectDeleteResponse = await _subjectService.DeleteAsync(id);
        if (subjectDeleteResponse.IsSuccess)
            NotifySuccessLocalized(subjectDeleteResponse.Message);
        else
            NotifyErrorLocalized(subjectDeleteResponse.Message);

        return Json(subjectDeleteResponse);
    }

}

BAExamApp.MVC/Areas/Admin/Views/Subject/CreatePartialView.cshtml
@model AdminSubjectCreateVM

@{
    ViewData["Title"] = ViewLocalizer["Create_Subject"];
}

<div class="modal fade" id="createSubjectModal" tabindex="-1" aria-labelledby="ProductAdd" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@SharedLocalizer["Create_New_Subject"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-controller="Subject" asp-action="Create" class="form" id="create-subject">
                <div class="modal-body">
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label col-form-label-lg"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" type="text" class="form-control form-control-lg form-control-solid" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <a class="btn btn-light align-self-center ms-2" asp-controller="Subject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button class="btn btn-primary" type="submit">@SharedLocalizer["Save"]</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

BAExamApp.MVC/Areas/Admin/Views/Subject/Details.cshtml
@model AdminSubjectDetailVM

@{
    ViewData["Title"] = ViewLocalizer["Subject_Details"];
}
<div class="card mb-5 mb-xl-10" id="kt_profile_details_view">
    <div class="card-header cursor-pointer">
        <div class="card-title m-0">
            <h5 class="text-center">@ViewLocalizer["Subject_Details"]</h5>
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-secondary align-self-center ms-2" asp-controller="Subject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
            <a class="btn btn-primary align-self-center ms-2" data-bs-toggle="modal" data-bs-target="#updateSubjectModal" data-subject-id="@Model.Id" data-subject-name="@Model.Name">
                @SharedLocalizer["Update"]
            </a>
            <a class="btn btn-danger align-self-center ms-2 deleteAction" data-id="@Model.Id"> @SharedLocalizer["Delete"] </a>
        </div>
    </div>
    <div class="card-body p-9">
        <div class="row mb-7">
            <label class="col-lg-2 fw-bold text-muted">@SharedLocalizer["Subject_Name"]:</label>
            <div class="col-lg-10 fv-row">
                <span class="fw-bold text-gray-800 fs-6">@Model.Name</span>
            </div>
        </div>
        <div class="row mb-7">
            <label class="col-lg-2 fw-bold text-muted">@SharedLocalizer["Products_That_Include_Subject"]:</label>
            <div class="col-lg-10">
                <span class="fw-bold fs-6 text-gray-800">
                    @foreach (var product in Model.Products)
                    {
                        <tr>
                            <td class="categories">
                                <span style="font-size: 15px;" class="post_category">@product.Name</span>
                            </td>
                        </tr>
                    }
                </span>
            </div>
        </div>
    </div>
</div>

<partial name="~/Areas/Admin/Views/Subject/UpdatePartialView.cshtml" model="new AdminSubjectUpdateVM()" />

@section Scripts
    {

    <script src="~/js/updateSubject.js"></script>
    <script src="~/lib/limonte-sweetalert2/sweetalert2.all.js"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> *@
    <script>
        var localizedTexts = {
            confirmTitle: '@SharedLocalizer["Confirm_Delete_Title"]', // "fullName adlı admini silmek istediğinize emin misiniz?"
            confirmText: '@SharedLocalizer["Confirm_Delete_Text"]', // "Bu işlem geri alınamaz!"
            confirmButtonText: '@SharedLocalizer["Confirm_Button_Text"]', // "Evet, sil!"
            cancelButtonText: '@SharedLocalizer["Cancel_Button_Text"]' // "Hayır, iptal et"
        };
        $(document).ready(function () {
            $(".deleteAction").click(function () {
                const id = $(this).data("id");
                Swal.fire({
                    title: `${localizedTexts.confirmTitle}`,
                    text: localizedTexts.confirmText,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: localizedTexts.confirmButtonText,
                    cancelButtonText: localizedTexts.cancelButtonText
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: "@Url.Action("Delete")" + "?id=" + id,
                            success: function (result) {
                                if (result.isSuccess) {
                                    Swal.fire({
                                        icon: 'success',
                                        title: 'Başarılı',
                                        text: 'Silme işlemi başarıyla tamamlandı!'
                                    });
                                    setTimeout(() => location.href = "@Url.Action("index")", 2000);
                                } else {
                                    Swal.fire({
                                        icon: 'error',
                                        title: 'Hata',
                                        text: 'Silme işlemi sırasında bir hata oluştu!',
                                        confirmButtonText: 'Tamam'
                                    });
                                }
                            },
                            error: function () {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Hata',
                                    text: 'Silme işlemi sırasında bir hata oluştu!'
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>
}

BAExamApp.MVC/Areas/Admin/Views/Subject/UpdatePartialView.cshtml
@model AdminSubjectUpdateVM

@{
    ViewData["Title"] = ViewLocalizer["Update"];
}

<div class="modal fade" id="updateSubjectModal" tabindex="-1" aria-labelledby="updateSubjectModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form asp-controller="Subject" asp-action="Update" method="post" id="updateSubjectForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateSubjectModalLabel">@SharedLocalizer["Subject_Update"]</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3">
                        <label asp-for="Name" class="form-label">@SharedLocalizer["Subject_Name"]</label>
                        <input asp-for="Name" type="text" class="form-control" required>
                    </div>
                    <input asp-for="Id" type="hidden" />
                </div>
                <div class="modal-footer">
                    <a class="btn btn-primary align-self-center ms-2" asp-controller="Subject" asp-action="Index">@SharedLocalizer["Back_List"]</a>
                    <button type="submit" class="btn btn-success">@SharedLocalizer["Update"]</button>
                </div>
            </form>
        </div>
    </div>
</div>